name: "Bug Report"
description: "Report a bug or unexpected problem"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thank you for finding a bug! Please fill out this form to help us fix it."
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "How can we make the bug happen on our end?"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen instead?"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: "Browser (if applicable)"
      description: "Which browser did you see this on?"
      multiple: true
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "N/A"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs or Error Messages"
      description: "Please paste any relevant console logs or error messages."
      render: "shell"

