name: "Feature Request"
description: "Suggest a new idea or enhancement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to suggest a new feature!"
  - type: textarea
    id: problem
    attributes:
      label: "What problem is this feature solving?"
      description: "Is your feature request related to a problem? (e.g., 'I'm always frustrated when...')"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "What is your proposed solution?"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false

